'use client'

import './globals.css'
import { Providers } from "./providers";
import { Inter } from 'next/font/google'
import { CacheProvider } from '@chakra-ui/next-js'
import { ChakraProvider } from '@chakra-ui/react'
import Footer from '../components/Footer'
import Header from '../components/Header'

const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Task Management App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
    <html lang="en">
      <Providers >
      <body className={inter.className}>
      <Header/>
        <main className='flex-1 flex flex-col p-4'>
            {children}
        </main>
        <Footer/>
      </body>
      </Providers>
    </html>
   
  )
}
